#!/bin/bash
# SmartHire AI - Quick Start Demo Guide
# This guide walks through all features in 5 minutes

echo "🎯 SmartHire AI - Hackathon Demo Guide"
echo "======================================"
echo ""
echo "App is running at: http://localhost:5173"
echo "Backend API: http://localhost:5000"
echo ""

echo "📋 DEMO FLOW (5-10 minutes)"
echo ""

echo "1️⃣ CREATE A JOB"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  1. Click 'Post New Job' button"
echo "  2. Fill in:"
echo "     - Title: Full-Stack Developer"
echo "     - Description: Seeking experienced developer with React & Node.js"
echo "     - Requirements: React, Node.js, PostgreSQL, REST APIs, Docker"
echo "  3. Click Submit"
echo "  → Job appears in dashboard grid"
echo ""

echo "2️⃣ UPLOAD SINGLE RESUME (Show AI Analysis)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  1. Click on the job card"
echo "  2. Click 'Analyze' or '➕ Add Resume'"
echo "  3. Enter candidate name"
echo "  4. Upload any PDF resume"
echo "  5. Click 'Analyze Resume'"
echo "  → See AI scoring with:"
echo "    - Match percentage"
echo "    - AI summary"
echo "    - Matched skills (green badges)"
echo "    - Missing keywords (red badges)"
echo "    - Interview questions"
echo ""

echo "3️⃣ VIEW ALL CANDIDATES (Results Dashboard)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  1. From ResumeAnalyzer, click 'View All Candidates'"
echo "  2. OR click 'View X Candidates' on dashboard"
echo "  → See:"
echo "    - Top 3 candidates highlighted in gradient box"
echo "    - Full candidates table"
echo "    - Filter by High/Medium/Low match"
echo "    - Statistics cards at bottom"
echo ""

echo "4️⃣ VIEW CANDIDATE PROFILE (Full Details)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  1. Click 'View Details' on any candidate"
echo "  → See complete profile:"
echo "    - Gradient hero with score"
echo "    - Match analysis bar"
echo "    - AI summary"
echo "    - Missing keywords"
echo "    - Interview questions"
echo "    - Resume preview"
echo "    - Notes section (editable, saves to localStorage)"
echo "    - Email contact button"
echo ""

echo "5️⃣ BULK UPLOAD MULTIPLE RESUMES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  1. Go back to dashboard"
echo "  2. Click '📦 Bulk Upload' on job card"
echo "  3. Drag-drop 3-5 PDF files into the zone"
echo "    (OR click 'Browse Files' to select)"
echo "  4. Click 'Upload X Resumes'"
echo "  → See:"
echo "    - Upload progress"
echo "    - Results summary (total, successful, avg score)"
echo "    - Individual file status"
echo "    - Navigate to view all candidates button"
echo ""

echo "✨ FEATURES TO HIGHLIGHT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 PREMIUM FEATURES DEMONSTRATED:"
echo "  1. ✅ Results Dashboard - Sortable, filterable candidates table"
echo "  2. ✅ Bulk Upload - Parallel processing of multiple files"
echo "  3. ✅ Match Breakdown - Visual skill matching (green/red badges)"
echo "  4. ✅ Candidate Details - Complete profile with notes"
echo "  5. ✅ Top Candidates - #1, #2, #3 recommended at top of list"
echo "  6. ✅ Complete Routing - 6 pages seamlessly integrated"
echo ""

echo "🎨 DESIGN HIGHLIGHTS:"
echo "  - Gradient hero sections (color-coded by score)"
echo "  - Color badges (Green=High, Yellow=Medium, Red=Low)"
echo "  - Responsive design (works on mobile too)"
echo "  - Progress bars and charts"
echo "  - Professional UI with Tailwind CSS"
echo ""

echo "🤖 AI FEATURES:"
echo "  - Google Gemini 2.0 Flash model"
echo "  - Deterministic scoring (temperature=0)"
echo "  - Automated interview question generation"
echo "  - Missing keywords identification"
echo "  - Skill match analysis"
echo "  - Smart fallback (mock mode if quota exceeded)"
echo ""

echo "📱 DATA PERSISTENCE:"
echo "  - Jobs stored in SQLite database"
echo "  - Candidates persist after upload"
echo "  - Notes saved to browser localStorage"
echo "  - All data survives page refresh"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🚀 READY TO DEMO? START HERE:"
echo ""
echo "1. Make sure servers are running (npm run dev)"
echo "2. Open http://localhost:5173 in browser"
echo "3. Follow the 5 steps above"
echo "4. Show judges each feature in order"
echo ""
echo "⏱️  Total demo time: 5-10 minutes"
echo "📊 Each feature takes ~1-2 minutes to demonstrate"
echo ""
echo "💡 PRO TIPS:"
echo "  - Have 2-3 sample PDFs ready to upload"
echo "  - Demo bulk upload with multiple files (shows parallelization)"
echo "  - Click edit notes → show localStorage persistence (refresh page)"
echo "  - Mention fallback to mock AI if quota exceeded"
echo "  - Highlight responsive design by resizing browser"
echo ""
echo "✅ Good luck! You've got a 9/10 project here!"
echo ""
